name: tests
on: push
jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - run: NODE_OPTIONS=--experimental-vm-modules npx jest
  eslint:
    runs-on: ubuntu-latest
    steps:
      - run: npx eslint .